watch_stylesheet: true
watch_config: true
debug: false

bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["home", "glazewm_workspaces", "cpu", "gpu", "memory"]
      center: ["weather", "clock", "media"]
      right:
        [
          "taskbar",
          "systray",
          "wifi",
          "bluetooth",
          "volume",
          "microphone",
          "battery",
          "power_menu",
        ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\uf17a</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "C:\\Users\\ashis\\Downloads" }
        - { title: "Documents", path: "C:\\Users\\ashis\\Documents" }
        - { title: "Pictures", path: "C:\\Users\\ashis\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "#585b70"
      distance: 6
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> CPU: {info[percent][total]} % | {info[histograms][cpu_percent]}"
      label_alt: "<span>\uf437</span> CPU: {info[cores][total]} Cores |{info[freq][current]}  MHz"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> RAM: {virtual_mem_free}/{virtual_mem_total}"
      label_alt: "<span>\uf4bc</span> RAM VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "<span>\uf4bc</span> GPU: {info[utilization]} % | {info[histograms][utilization]}"
      label_alt: "<span>\uf4bc</span> GPU: {info[temp]}°C | {info[mem_used]} / {info[mem_total]}"
      update_interval: 2000
      gpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_label"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {title} - {artist}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      max_field_size:
        label: 40
        label_alt: 60
      show_thumbnail: false
      controls_only: false
      controls_left: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "#585b70"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 10
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%a, %b %d - %I:%M %p}"
      label_alt: "{%A %d %B %Y %H:%M:%S}"
      timezones: []
    calendar:
      blur: True
      round_corners: True
      round_corners_type: "normal"
      border_color: "#585b70"
      alignment: "center"
      direction: "down"
      distance: 6
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 20
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 5
        bottom: 0
        right: 5
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "▼"
      label_expanded: "▶"
      label_position: "left" # Can be "left" or "right"
      icon_size: 20 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: true
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      btn_shadow:
        enabled: true
        color: "green"
        radius: 3
        offset: [1, 1]
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: " time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span> {wifi_icon} </span> {wifi_name}"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec explorer ms-availablenetworks:"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      wifi_icons:
        [
          "\udb82\udd2e",
          "\udb82\udd1f",
          "\udb82\udd22",
          "\udb82\udd25",
          "\udb82\udd28",
        ]
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "4195c481fcd445d98b171347262903" # Get your free API key from https://www.weatherapi.com/
      show_alerts: true
      tooltip: true
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      units: "imperial" # Can be 'metric' or 'imperial'
      location: "Fort Lee, NJ, USA" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyDay: "\ue30a"
        snowyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: true # Set to False to disable hourly forecast
        time_format: "24h" # can be 12h or 24h
        hourly_point_spacing: 76
        hourly_icon_size: 32 # better to set 16, 32 or 64 for better quality
        icon_smoothing: true # should be true for smoother icon or false for sharper icon if using 16, 32 or 64 for hourly_icon_size
        temp_line_width: 2 # can be 0 to hide the temperature line
        current_line_color: "#8EAEE8"
        current_line_width: 1 # can be 0 to hide the current hour line
        current_line_style: "dot"
        hourly_gradient:
          enabled: false
          top_color: "#8EAEE8"
          bottom_color: "#2A3E68"
        hourly_forecast_buttons: # Optional hourly forecast data type toggle buttons, default disabled
          enabled: true # Set to false to hide the buttons
          default_view: "temperature" # Default view when opening the weather card. Options: "temperature", "rain", "snow"
          temperature_icon: "\udb81\udd99"
          rain_icon: "\udb81\udd96"
          snow_icon: "\udb81\udd98"
        weather_animation:
          enabled: false
          snow_overrides_rain: true
          temp_line_animation_style: both # can be "rain", "snow", "both", or "none"
          rain_effect_intensity: 1.0 # 0.01 - 10.0
          snow_effect_intensity: 1.0 # 0.01 - 10.0
          scale_with_chance: true
          enable_debug: false
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span> {device_count}"
      label_alt: "{device_name}"
      label_no_device: "No devices connected"
      label_device_separator: ", "
      max_length: 10
      max_length_ellipsis: "..."
      icons:
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      device_aliases:
        - name: "T5.0"
          alias: "\uf025"
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\udb81\udf5f "
        - "\uf026 "
        - "\uf026 "
        - "\uf027 "
        - "\uf028 "
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {level}"
      mute_text: "mute"
      icons:
        normal: "\uf130"
        muted: "\uf131"
      mic_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_mic_menu"
        on_middle: "toggle_label"
        on_right: "toggle_mute"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\udb82\udd06"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\udb82\udd06", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb80\udee9</span>"
      image_path: "C:\\Users\\ashis\\windots\\walls"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 296
        image_per_page: 6
        show_buttons: false
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 20
        enable_cache: true
